name: "\U0001F41B Bug Report"
description: 'Found an unexpected behavior?'
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Before submitting new issue please search [here](../issues?q=is%3Aissue) to see if simmilar issue already exists'
      options:
        - label: "I've not found one"
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Current behavior'
      description: 'Describe unwanted behaviour'

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Expected behavior'
      description: 'Describe expected outcome'

  - type: input
    validations:
      required: true
    attributes:
      label: 'Minimum reproduction code'
      description: 'An URL to some Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project that reproduces your issue. [Wtf is a minimum reproduction?](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction)'
      placeholder: 'https://github.com/...'

  - type: markdown
    attributes:
      value: |
        ---

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: 'Package'
      description: |
        Which package (or packages) do you think your issue is related to?
      options:
        - label: '<code>@unifig/core</code>'
        - label: '<code>@unifig/nest</code>'
        - label: '<code>@unifig/env</code>'
        - label: 'Not sure'

  - type: input
    attributes:
      label: 'Unifig version'
      description: |
        Which version of `@Unifig/core` are you using?
      placeholder: '2.1.3'

  - type: input
    attributes:
      label: 'Node.js version'
      description: 'Which version of Node.js are you using?'
      placeholder: '16.17.0'

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: 'Used operating systems'
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    attributes:
      label: 'Other'
      description: |
        Logs, OS version, IDE, package manager, etc.
