name: pr-push

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  pr-build:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      changed_packages: ${{ steps.changed_packages.outputs.changed_packages }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        env:
          PULL_REQUEST_COMMITS: ${{ github.event.pull_request.commits }}
        with:
          fetch-depth: $(( $PULL_REQUEST_COMMITS + 1 ))
      - name: Check for changes
        id: changed_packages
        run: echo "::set-output name=changed_packages::$(git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} --name-only "./packages/**" | wc -l | xargs)"
      - name: Load yarn & node modules
        if: steps.changed_packages.outputs.changed_packages != '0'
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Cache build output
        if: steps.changed_packages.outputs.changed_packages != '0'
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-pr${{ github.event.number }}-${{ hashFiles('./packages/**') }}
      - name: Build changed projects
        if: steps.changed_packages.outputs.changed_packages != '0'
        run: yarn lerna run build --stream --since origin/${{ github.base_ref }}...origin/${{ github.head_ref }} --include-dependencies

  pr-lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        env:
          PULL_REQUEST_COMMITS: ${{ github.event.pull_request.commits }}
        with:
          fetch-depth: $(( $PULL_REQUEST_COMMITS + 1 ))
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Run lint on changed files
        run: yarn eslint $(git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} --diff-filter=ACM --name-only \"*.ts\" | xargs)

  unit-tests:
    runs-on: ubuntu-latest
    needs: pr-build
    if: needs.pr-build.outputs.changed_packages != '0'
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-pr${{ github.event.number }}-${{ hashFiles('./packages/**') }}
      - name: Cache coverage output
        uses: actions/cache@v3
        env:
          cache-name: cache-coverage
        with:
          path: ./coverage/coverage-final.json
          key: coverage-${{ hashFiles('./packages/*/lib/**') }}
      - name: Run unit tests with coverage
        run: yarn run test:cov

  pr-e2e-tests:
    runs-on: ubuntu-latest
    needs: pr-build
    if: needs.pr-build.outputs.changed_packages != '0'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        env:
          PULL_REQUEST_COMMITS: ${{ github.event.pull_request.commits }}
        with:
          fetch-depth: $(( $PULL_REQUEST_COMMITS + 1 ))
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-pr${{ github.event.number }}-${{ hashFiles('./packages/**') }}
      - name: Run e2e tests in changed projects
        run: yarn lerna run test:e2e --stream --since origin/${{ github.base_ref }}...origin/${{ github.head_ref }} --include-dependents

  codecov:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Load coverage output
        uses: actions/cache@v3
        env:
          cache-name: cache-coverage
        with:
          path: ./coverage/coverage-final.json
          key: coverage-${{ hashFiles('./packages/*/lib/**') }}
      - name: Upload report to codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          verbose: true
