name: release

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Cache build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Build changed projects
        run: yarn lerna run --stream build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Run e2e tests in changed projects
        run: yarn lerna run test:e2e --stream

  preview:
    runs-on: ubuntu-latest
    needs: setup
    concurrency:
      group: create-release
      cancel-in-progress: false
    outputs:
      changed_packages: ${{ steps.changed_packages.outputs.changed_packages }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Check for changes
        id: changed_packages
        run: echo "::set-output name=changed_packages::$(yarn lerna changed -p | wc -l | xargs)"
      - name: Preview versions changes
        run: yarn lerna version --no-push --no-git-tag-version -y
      - name: Preview changelogs
        run: git --no-pager diff "*CHANGELOG.md"

  release:
    runs-on: ubuntu-latest
    if: needs.preview.outputs.changed_packages != '0'
    environment: prod
    needs:
      - e2e-tests
      - preview
    concurrency:
      group: create-release
      cancel-in-progress: false
    env:
      BOT_NAME: github-actions[bot]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Load yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Load build output
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ./packages/*/dist
          key: packages-${{ hashFiles('./packages/**') }}
      - name: Configure git client
        run: |
          git config --local user.name $BOT_NAME
          git config --local user.email ${BOT_NAME}@users.noreply.github.com
      - name: Publish version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn lerna version -y
