name: setup

on: workflow_call

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache yarn & node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-node-modules
        with:
          path: ./node_modules
          key: lock-${{ hashFiles('./yarn.lock') }}
      - name: Install node_modules
        run: if [ ! -d ./node_modules ]; then yarn install --immutable; fi
